# Generated by Django 5.0.7 on 2024-07-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='productos',
            field=models.ManyToManyField(to='carrito.producto'),
        ),
    ]
