# Generated by Django 5.0.7 on 2024-07-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_remove_itemcarrito_productos_itemcarrito_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='nombre',
            new_name='name',
        ),
    ]
